# Generated by Django 3.2 on 2023-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_sectorempresarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('IdMoneda', models.AutoField(db_column='IdMoneda', primary_key=True, serialize=False)),
                ('Simbolo', models.CharField(max_length=10)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='TipoActividadUsuario',
            fields=[
                ('IdTipoActividadUsuario', models.AutoField(db_column='IdTipoActividadUsuario', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TipoActividadUsuario',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('IdTipoUsuario', models.AutoField(db_column='IdTipoUsuario', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TipoUsuario',
            },
        ),
        migrations.RemoveField(
            model_name='sectorempresarial',
            name='id',
        ),
        migrations.AddField(
            model_name='sectorempresarial',
            name='IdSectorEmpresarial',
            field=models.AutoField(db_column='IdSectorEmpresarial', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='sectorempresarial',
            table='SectorEmpresarial',
        ),
    ]
