# Generated by Django 3.2 on 2023-10-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_auto_20231024_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasEmpleos',
            fields=[
                ('IdCategoriasEmpleos', models.AutoField(db_column='IdCategoriasEmpleos', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CategoriasEmpleos',
            },
        ),
    ]
