# Generated by Django 3.2 on 2023-10-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_categoriasempleos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProyectos',
            fields=[
                ('IdCategoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CategoriaProyectos',
            },
        ),
    ]
