# Generated by Django 3.2 on 2023-10-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_empresa_institucioneducativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorempresarial',
            old_name='Nombre',
            new_name='NombreS',
        ),
    ]
