# Generated by Django 3.2 on 2023-10-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0007_rename_nombre_sectorempresarial_nombres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorempresarial',
            old_name='NombreS',
            new_name='Nombre',
        ),
    ]
