# Generated by Django 3.2 on 2023-10-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0008_rename_nombres_sectorempresarial_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Correo',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucioneducativa',
            name='Correo',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
