# Generated by Django 3.2 on 2023-10-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20231027_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='FechaPublicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
