# Generated by Django 3.2 on 2023-10-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_proyecto_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='AutoresCV',
            field=models.FileField(blank=True, null=True, upload_to='media/autores-cv/'),
        ),
    ]
