# Generated by Django 3.2 on 2023-10-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_proyecto_autorescv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='AutoresCV',
            field=models.ImageField(blank=True, null=True, upload_to='autores-cv/'),
        ),
    ]
