# Generated by Django 3.2 on 2023-10-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_postulacionempleo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionempleo',
            name='Estado',
            field=models.BooleanField(default=False),
        ),
    ]
